title: What I'm Doing to Prepare for the Zombie Apocalypse
description: The musings of a developer learning to become a maker.

url: https://maker.limeblast.co.uk
baseurl: ""
paginate_path: "page:num/"
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-figure
paginate: 10

navigation:
  - title: Home
    url: /
  - title: About
    url: /about-this-blog/
  - title: Contact
    url: /contact/

social:
  github: limeblast
  twitter: limeblast
  facebook: limeblast
  email: daniel@limeblast.co.uk

google_analytics: "UA-26654246-3"

jekyll-figure:
  paragraphs: false
